/* ============================================================
   INOVA BEAUTY — English
   Chave = frase em português (como está no site). Valor = tradução.
   O que não estiver aqui fica em português (nunca inventa).
   ============================================================ */
window.INOVA_DIC = window.INOVA_DIC || {};
window.INOVA_DIC.en = {

/* ---------- navegação / rodapé ---------- */
"Home": "Home",
"Serviços": "Services",
"Preçário": "Price list",
"Processos": "How it works",
"Sobre": "About",
"Sobre nós": "About us",
"Contato": "Contact",
"Localização": "Location",
"Navegação": "Navigation",
"Navegação principal": "Main navigation",
"Navegação da app": "App navigation",
"Navegação dos destaques": "Highlights navigation",
"Contactos": "Contacts",
"Clientes": "Clients",
"Área reservada": "Staff area",
"Todos os serviços →": "All services →",
"Ver todos os serviços": "See all services",
"Ver site completo": "View full site",
"© 2026 Inova Beauty — Todos os direitos reservados. ·": "© 2026 Inova Beauty — All rights reserved. ·",
"Beleza, precisão e cuidado em cada detalhe.": "Beauty, precision and care in every detail.",
"Beleza, precisão e cuidado.": "Beauty, precision and care.",
"Beleza, precisão e cuidado em cada detalhe. Especialistas em sobrancelhas, pestanas e micropigmentação.": "Beauty, precision and care in every detail. Specialists in eyebrows, lashes and micropigmentation.",

/* ---------- botões / ações ---------- */
"Agendar": "Book now",
"Marcar horário": "Book an appointment",
"Marcar horário online": "Book online",
"Marcação online": "Online booking",
"✨ Marcar horário": "✨ Book an appointment",
"✨ Marcar horário online": "✨ Book online",
"✨ Fazer marcação online": "✨ Book online",
"✨ Marcar este serviço": "✨ Book this service",
"✨ Confirmar marcação": "✨ Confirm booking",
"Fazer marcação": "Book now",
"Confirmar marcação": "Confirm booking",
"Entrar": "Log in",
"Iniciar sessão": "Log in",
"Entrar / Registar-se": "Log in / Sign up",
"👤 Entrar": "👤 Log in",
"Registar-se": "Sign up",
"Criar conta": "Create account",
"Criar a minha conta": "Create my account",
"ainda não tem conta?": "don't have an account yet?",
"Já tem conta? Iniciar sessão": "Already have an account? Log in",
"Sair": "Log out",
"Guardar": "Save",
"Guardar alterações": "Save changes",
"Adicionar": "Add",
"Adicionar selo": "Add stamp",
"Enviar": "Send",
"Enviar foto": "Send photo",
"Publicar": "Post",
"Remover": "Remove",
"Trocar foto": "Change photo",
"📷 Escolher foto": "📷 Choose photo",
"Escolher personagem": "Choose character",
"Apagar conta": "Delete account",
"Alterar senha": "Change password",
"Alterar senha (por email)": "Change password (by email)",
"Esqueci a minha senha": "I forgot my password",
"Explorar": "Explore",
"Saber mais": "Learn more",
"Ver detalhes": "See details",
"Ver preços": "See prices",
"Ver preços deste serviço": "See prices for this service",
"Ver preço no preçário": "See price in the price list",
"Ver preçário completo": "See full price list",
"Ver serviços": "See services",
"Ver como é feito": "See how it's done",
"Ver passo a passo": "See step by step",
"Conhecer o serviço": "Discover the service",
"Conhecer a Inova Beauty": "Discover Inova Beauty",
"Toque para abrir": "Tap to open",
"Fechar chat": "Close chat",
"Abrir chat online": "Open live chat",
"Abrir menu": "Open menu",
"Pedir localização": "Ask for location",
"Usar o meu prémio nesta marcação": "Use my reward on this booking",

/* ---------- home / hero ---------- */
"Marcação online": "Online booking",
"Marque o seu horário <em>online</em>, em 1 minuto": "Book your appointment <em>online</em>, in 1 minute",
"Escolha o serviço, o dia e a hora e confirme — sem telefonemas, sem esperas. É a forma mais rápida e organizada de garantir a sua vaga.": "Choose the service, day and time and confirm — no phone calls, no waiting. It's the fastest and most organised way to secure your spot.",
"Rápido · Sem esperas · Escolha o seu horário": "Fast · No waiting · Choose your time",
"Tem alguma dúvida? Fale connosco no WhatsApp →": "Have a question? Chat with us on WhatsApp →",
"Tem dúvidas? Fale connosco no WhatsApp →": "Have questions? Chat with us on WhatsApp →",
"Sobrancelhas perfeitas <em>ao acordar</em>": "Perfect eyebrows <em>when you wake up</em>",
"Técnica fio a fio ultra natural, com consulta de avaliação deduzida no valor do procedimento. Veja o passo a passo sem mistérios.": "Ultra-natural hair-by-hair technique, with the assessment consultation deducted from the procedure price. See the step-by-step, no mysteries.",
"🎂 Presente de aniversário": "🎂 Birthday gift",
"10% de desconto no seu <em>aniversário</em>": "10% off on your <em>birthday</em>",
"Crie a sua conta gratuita e receba automaticamente um cupom de 10% na semana do seu aniversário. É o nosso mimo para si.": "Create your free account and automatically receive a 10% coupon in your birthday week. It's our little gift to you.",
"Beleza, precisão e <em>cuidado</em> em cada detalhe": "Beauty, precision and <em>care</em> in every detail",
"Especialistas em sobrancelhas, pestanas, micropigmentação e depilação com linha. Realce a sua beleza natural com quem trata cada detalhe como arte.": "Specialists in eyebrows, lashes, micropigmentation and threading. Enhance your natural beauty with someone who treats every detail as art.",
"Destaques Inova Beauty": "Inova Beauty highlights",
"Slide anterior": "Previous slide",
"Slide seguinte": "Next slide",
"Ir para o slide 1": "Go to slide 1",
"Ir para o slide 2": "Go to slide 2",
"Ir para o slide 3": "Go to slide 3",
"Ir para o slide 4": "Go to slide 4",

/* ---------- home / secções ---------- */
"O seu rosto merece um olhar de especialista": "Your face deserves an expert's eye",
"Na Inova Beauty unimos técnica, visagismo e produtos de excelência para realçar o que a natureza lhe deu. Cada atendimento é personalizado — porque não há dois rostos iguais.": "At Inova Beauty we combine technique, face styling and premium products to enhance what nature gave you. Every appointment is personalised — because no two faces are alike.",
"Profissionais especializadas e certificadas": "Specialised and certified professionals",
"Técnicas atuais: threading, laminação, lifting e micropigmentação": "Up-to-date techniques: threading, lamination, lift and micropigmentation",
"Ambiente acolhedor, higiene e produtos premium": "Welcoming space, hygiene and premium products",
"O que fazemos por si": "What we do for you",
"Design com linha, laminação, coloração e tratamentos de nutrição para umas sobrancelhas perfeitas.": "Threading, lamination, colouring and nourishing treatments for perfect eyebrows.",
"Lifting, permanente e tintura para um olhar marcante todos os dias, sem esforço.": "Lift, perm and tint for a striking look every day, effortlessly.",
"Micropigmentação de sobrancelhas fio a fio, com resultado natural e duradouro.": "Hair-by-hair eyebrow micropigmentation, with a natural, long-lasting result.",
"Hidratação profunda e brilho para os lábios, com ou sem cor — lábios nutridos, macios e luminosos.": "Deep hydration and shine for the lips, with or without colour — nourished, soft and luminous lips.",
"Depilação com linha para rosto e sobrancelhas — precisão total, sem químicos e ideal para peles sensíveis.": "Threading for face and eyebrows — total precision, no chemicals, ideal for sensitive skin.",
"Depilação a laser para rosto e corpo, com resultados progressivos e duradouros.": "Laser hair removal for face and body, with progressive, long-lasting results.",
"Preços claros, sem surpresas": "Clear prices, no surprises",
"Consulte o preçário completo com todos os serviços e packs especiais — valores em euro (€).": "See the full price list with all services and special packages — prices in euros (€).",
"Pronta para realçar a sua beleza?": "Ready to enhance your beauty?",
"Marque o seu horário online em 1 minuto — escolha o serviço, o dia e a hora. Sem telefonemas, sem esperas.": "Book your appointment online in 1 minute — choose the service, day and time. No phone calls, no waiting.",

/* ---------- serviços ---------- */
"Os nossos serviços": "Our services",
"Toque na imagem de cada serviço para ver as opções disponíveis — e clique para conhecer os detalhes e preços.": "Tap each service image to see the available options — and click to see the details and prices.",
"Sobrancelhas": "Eyebrows",
"Pestanas": "Lashes",
"Micropigmentação": "Micropigmentation",
"Lábios": "Lips",
"Lábios (Hidraglos)": "Lips (Hidraglos)",
"Threading": "Threading",
"Depilação a Laser": "Laser hair removal",
"Toque para abrir": "Tap to open",
"Ver preços": "See prices",
"Ver tudo em Sobrancelhas": "See all in Eyebrows",
"Ver tudo em Pestanas": "See all in Lashes",
"Ver tudo em Micropigmentação": "See all in Micropigmentation",
"Ver tudo em Lábios": "See all in Lips",
"Mostrar sub-serviços de Sobrancelhas": "Show Eyebrow sub-services",
"Mostrar sub-serviços de Pestanas": "Show Lash sub-services",
"Mostrar sub-serviços de Micropigmentação": "Show Micropigmentation sub-services",
"Mostrar sub-serviços de Lábios": "Show Lip sub-services",
"Alisamento": "Straightening",
"Alisamento de Sobrancelhas": "Eyebrow straightening",
"Brow Lamination": "Brow Lamination",
"Coloração": "Colouring",
"Coloração de Sobrancelhas": "Eyebrow colouring",
"Coloração de Sobrancelhas (Henna / Tintura / Descoloração)": "Eyebrow colouring (Henna / Tint / Bleaching)",
"Lifting de Pestanas": "Lash Lift",
"Lifting + Tintura de Pestanas": "Lash Lift + Tint",
"Permanente de Pestanas": "Lash Perm",
"Tintura de Pestanas": "Lash Tint",
"Extensão de Pestanas": "Lash Extensions",
"Micropigmentação de Sobrancelhas": "Eyebrow micropigmentation",
"Micro de Sobrancelhas": "Eyebrow micro",
"Hidraglos": "Hidraglos",
"Hidraglos de Lábios": "Lip Hidraglos",
"Threading de Sobrancelhas": "Eyebrow threading",
"Threading (rosto)": "Threading (face)",
"Threading (Depilação com Linha)": "Threading (thread hair removal)",
"Teen (até 18 anos)": "Teen (up to 18)",
"Tratamentos": "Treatments",
"Produtos": "Products",
"Outro (indico na mensagem)": "Other (I'll specify)",

/* ---------- página de serviço ---------- */
"Benefícios": "Benefits",
"Para quem é": "Who it's for",
"Vantagens": "Advantages",
"Preço": "Price",
"Preços": "Prices",
"A magia da linha": "The magic of the thread",
"Definição fio a fio": "Hair-by-hair definition",
"O threading é a técnica de depilação com linha que permite desenhar as sobrancelhas fio a fio, com uma precisão que a cera e a pinça não conseguem igualar.": "Threading is the thread hair-removal technique that shapes eyebrows hair by hair, with a precision wax and tweezers can't match.",
"Desenho preciso e simétrico, adaptado ao seu rosto": "Precise, symmetrical shape, tailored to your face",
"Sem químicos nem produtos agressivos": "No chemicals or harsh products",
"Ideal para peles sensíveis e com tendência a irritação": "Ideal for sensitive, irritation-prone skin",
"Resultado mais duradouro do que a pinça": "Longer-lasting result than tweezers",
"Para quem quer sobrancelhas definidas com um acabamento impecável — incluindo peles sensíveis, reativas ou em tratamento dermatológico.": "For anyone wanting defined eyebrows with a flawless finish — including sensitive, reactive or dermatologically-treated skin.",
"A laminação de sobrancelhas realinha e fixa os pelos na direção ideal, criando um efeito cheio, penteado e uniforme que dura semanas.": "Brow lamination realigns and sets the hairs in the ideal direction, creating a full, brushed-up, even effect that lasts for weeks.",
"A curvatura das suas pestanas naturais elevada desde a raiz — efeito de máscara e olhar aberto, sem extensões.": "Your natural lashes curled from the root — a mascara effect and open gaze, with no extensions.",
"A coloração dá cor, preenchimento e definição às sobrancelhas — da henna (que também pigmenta a pele) à tintura dos pelos e à descoloração para clarear e uniformizar.": "Colouring adds colour, fullness and definition to the eyebrows — from henna (which also tints the skin) to hair tint and bleaching to lighten and even them out.",
"O alisamento disciplina pelos rebeldes ou encaracolados, deixando as sobrancelhas alinhadas, suaves e fáceis de manter.": "Straightening tames unruly or curly hairs, leaving eyebrows aligned, smooth and easy to maintain.",
"Pigmentos semi-permanentes desenhados fio a fio com dermógrafo, corrigindo falhas com um resultado ultra natural.": "Semi-permanent pigments drawn hair by hair with a dermograph, correcting gaps with an ultra-natural result.",
"Fios aplicados um a um sobre as suas pestanas naturais, criando comprimento, curvatura e volume à sua medida.": "Lashes applied one by one onto your natural lashes, creating length, curl and volume made to measure.",
"Tratamento de hidratação Hidraglos para lábios nutridos, macios e luminosos — com ou sem cor.": "Hidraglos hydration treatment for nourished, soft and luminous lips — with or without colour.",
"Luz concentrada que atinge a raiz do pelo, reduzindo o crescimento sessão após sessão — resultados progressivos e duradouros.": "Concentrated light that reaches the hair root, reducing growth session after session — progressive, long-lasting results.",
"O tratamento que disciplina e realinha os pelos das sobrancelhas, criando o efeito cheio e penteado que dura semanas.": "The treatment that tames and realigns eyebrow hairs, creating a full, brushed-up effect that lasts for weeks.",
"Henna, tintura ou descoloração para dar cor, preenchimento e uniformidade às sobrancelhas com efeito natural.": "Henna, tint or bleaching to add colour, fullness and evenness to the eyebrows with a natural effect.",
"Uma técnica milenar que usa apenas uma linha de algodão torcida para remover os pelos pela raiz, com precisão fio a fio.": "An ancient technique using only a twisted cotton thread to remove hair from the root, with hair-by-hair precision.",
"Ficou com vontade de experimentar?": "Feeling like trying it?",
"Fale connosco no WhatsApp — esclarecemos qualquer dúvida antes de marcar.": "Chat with us on WhatsApp — we'll answer any question before you book.",
"Encontrou o serviço ideal?": "Found the perfect service?",
"Marque o seu horário online em 1 minuto e garanta já a sua vaga.": "Book online in 1 minute and secure your spot right away.",
"Marcação online em 1 minuto.": "Online booking in 1 minute.",
"Dúvidas? WhatsApp": "Questions? WhatsApp",

/* ---------- processos ---------- */
"Como é feito": "How it's done",
"Como é feito cada procedimento": "How each procedure is done",
"Saber o que esperar é o primeiro passo para relaxar. Escolha um procedimento e veja o passo a passo completo.": "Knowing what to expect is the first step to relaxing. Choose a procedure and see the full step-by-step.",
"Passo a passo": "Step by step",
"Sem mistérios": "No mysteries",
"Cuidados depois do procedimento": "Aftercare",
"Preparação da pele": "Skin preparation",
"Avaliação e desenho": "Assessment and shaping",
"Finalização": "Finishing",
"Limpeza suave da zona para remover oleosidade e maquilhagem, garantindo higiene e conforto.": "Gentle cleansing of the area to remove oil and make-up, ensuring hygiene and comfort.",
"Analisamos o formato do seu rosto e desenhamos a linha ideal das sobrancelhas, respeitando a sua simetria natural.": "We analyse your face shape and draw the ideal eyebrow line, respecting your natural symmetry.",
"Refinamos o desenho pelo a pelo até o contorno ficar perfeito e simétrico.": "We refine the shape hair by hair until the outline is perfect and symmetrical.",
"Aplicamos gel calmante e penteamos as sobrancelhas, mostrando o resultado ao espelho.": "We apply a soothing gel and brush the eyebrows, showing you the result in the mirror.",
"Hidrate a pele com um produto suave": "Moisturise the skin with a gentle product",
"Evite calor intenso, vapor e sol direto nas primeiras 24 horas": "Avoid intense heat, steam and direct sun for the first 24 hours",
"Não aplique maquilhagem na zona no próprio dia": "Don't apply make-up to the area on the same day",
"🕐 Duração média: ≈ 15–20 min": "🕐 Average duration: ≈ 15–20 min",
"🕐 Duração média: ≈ 15–20 minutos": "🕐 Average duration: ≈ 15–20 minutes",

/* ---------- sobre ---------- */
"A nossa história": "Our story",
"Mais do que estética, autoestima": "More than beauty — self-confidence",
"Por trás da Inova Beauty está a <strong>Thayana</strong> — apaixonada por realçar a beleza natural de cada pessoa. Especializada nas técnicas mais atuais de embelezamento do olhar — threading, laminação de sobrancelhas, lifting de pestanas e micropigmentação — entrega resultados precisos, naturais e duradouros.": "Behind Inova Beauty is <strong>Thayana</strong> — passionate about enhancing everyone's natural beauty. Specialised in the latest eye-beautifying techniques — threading, brow lamination, lash lift and micropigmentation — she delivers precise, natural and long-lasting results.",
"Cada cliente é única. Por isso, todos os nossos serviços começam com uma avaliação personalizada do seu rosto, tom de pele e estilo — para que o resultado seja perfeito para si.": "Every client is unique. That's why all our services start with a personalised assessment of your face, skin tone and style — so the result is perfect for you.",
"Atendimento personalizado e sem pressas": "Personalised, unhurried service",
"Higiene rigorosa e produtos de qualidade premium": "Strict hygiene and premium-quality products",
"Formação contínua nas técnicas mais recentes": "Ongoing training in the latest techniques",
"Venha conhecer-nos": "Come and meet us",
"Marque a sua visita online — escolha o dia e a hora em 1 minuto. Teremos todo o gosto em recebê-la.": "Book your visit online — pick the day and time in 1 minute. We'll be delighted to welcome you.",

/* ---------- contato / localização ---------- */
"Fale connosco": "Get in touch",
"A forma mais rápida de marcar é online, em 1 minuto. O WhatsApp fica para tirar dúvidas — respondemos rapidamente.": "The fastest way to book is online, in 1 minute. WhatsApp is for questions — we reply quickly.",
"A forma mais rápida — escolha serviço, dia e hora em 1 minuto.": "The fastest way — choose service, day and time in 1 minute.",
"Telefone": "Phone",
"Prefere ligar? Estamos disponíveis no horário de funcionamento.": "Prefer to call? We're available during opening hours.",
"Horário": "Opening hours",
"Segunda a Sábado<br>09h00 – 19h00": "Monday to Saturday<br>09:00 – 19:00",
"Marcações": "Bookings",
"Atendemos por marcação para lhe garantir um serviço sem esperas.": "We work by appointment to ensure a service with no waiting.",
"Pronta para marcar?": "Ready to book?",
"Marque o seu horário online em 1 minuto. Se tiver dúvidas, fale connosco no WhatsApp.": "Book online in 1 minute. If you have questions, chat with us on WhatsApp.",
"Onde estamos": "Where we are",
"Onde encontrar a Inova Beauty": "Where to find Inova Beauty",
"Morada": "Address",
"Estamos à sua espera num espaço pensado para o seu conforto.": "We're waiting for you in a space designed for your comfort.",
"Envie-nos mensagem no WhatsApp e partilhamos de imediato a localização exata do estúdio.": "Message us on WhatsApp and we'll instantly share the studio's exact location.",
"Venha visitar-nos": "Come and visit us",
"Marque o seu horário e receba a localização exata na hora.": "Book your appointment and get the exact location right away.",
"Dúvidas no WhatsApp: +351 919 277 205": "Questions on WhatsApp: +351 919 277 205",
"Telefone: +351 919 277 205": "Phone: +351 919 277 205",
"Tirar dúvidas no WhatsApp": "Ask questions on WhatsApp",
"Dúvidas? Fale connosco": "Questions? Talk to us",
"Dúvidas?": "Questions?",
"● Online — respondemos já": "● Online — we reply right away",

/* ---------- marcação (agendar) ---------- */
"Agendamento": "Booking",
"Preencha os dados e confirme — a sua marcação fica registada e confirmamos o seu horário em breve.": "Fill in your details and confirm — your booking is registered and we'll confirm your time shortly.",
"Nome": "Name",
"Nome*": "Name*",
"O seu nome": "Your name",
"Telemóvel": "Mobile",
"Telemóvel*": "Mobile*",
"Telemóvel* (obrigatório)": "Mobile* (required)",
"Serviço*": "Service*",
"Serviço (opcional)": "Service (optional)",
"Dia preferido*": "Preferred day*",
"Hora preferida*": "Preferred time*",
"Hora preferida* (30 em 30 min)": "Preferred time* (every 30 min)",
"Cupom (opcional)": "Coupon (optional)",
"Cupom de desconto (opcional)": "Discount coupon (optional)",
"Observações (opcional)": "Notes (optional)",
"Alguma informação que devamos saber?": "Anything we should know?",
"A sua marcação fica registada diretamente para o estúdio. Confirmamos o seu horário em breve.": "Your booking is registered directly with the studio. We'll confirm your time shortly.",
"Escolha o serviço, o dia e a hora — a marcação fica registada e confirmamos em minutos.": "Choose the service, day and time — the booking is registered and we confirm within minutes.",
"🎁 Tem um prémio para usar!": "🎁 You have a reward to use!",
"Sobrancelha Grátis": "Free eyebrows",
"Ganhou por completar 10 selos. Marque este serviço e não paga nada.": "You earned it by completing 10 stamps. Book this service and pay nothing.",

/* ---------- conta ---------- */
"A minha conta": "My account",
"Email": "Email",
"Email*": "Email*",
"Senha": "Password",
"A sua senha": "Your password",
"Senha* (mín. 6 caracteres)": "Password* (min. 6 characters)",
"Senha* (mín. 6)": "Password* (min. 6)",
"Confirmar senha*": "Confirm password*",
"Data de nascimento*": "Date of birth*",
"Data de nascimento* (obrigatória)": "Date of birth* (required)",
"Sexo": "Gender",
"Sexo*": "Gender*",
"Masculino": "Male",
"Feminino": "Female",
"Foto de perfil (opcional)": "Profile photo (optional)",
"Ou usamos um ícone": "Or we use an icon",
"1 conta por número — evita duplicados.": "1 account per number — avoids duplicates.",
"1 conta por número.": "1 account per number.",
"Para o seu cupom de aniversário 🎁": "For your birthday coupon 🎁",
"Para receber o seu voucher de aniversário 🎁": "To receive your birthday voucher 🎁",
"⚙️ Configurações da conta": "⚙️ Account settings",
"🔒 A sua senha é protegida com criptografia (SHA-256 + salt) e os dados ficam guardados apenas neste dispositivo — nunca são enviados para terceiros.": "🔒 Your password is protected with encryption (SHA-256 + salt) and your data is stored only on this device — never shared with third parties.",
"🔒 Senha protegida com criptografia (SHA-256 + salt), guardada só neste dispositivo.": "🔒 Password protected with encryption (SHA-256 + salt), stored only on this device.",

/* ---------- app ---------- */
"Início": "Home",
"Marcar": "Book",
"Feed": "Feed",
"Cartão": "Card",
"Conta": "Account",
"Cartão de selos": "Stamp card",
"WhatsApp": "WhatsApp",
"Comunidade": "Community",
"Comunidade Inova": "Inova Community",
"Olá!": "Hello!",
"Olá! 👋": "Hello! 👋",
"Bem-vinda à Inova Beauty.": "Welcome to Inova Beauty.",
"Beleza, precisão e cuidado.": "Beauty, precision and care.",
"Inova Beauty no seu telemóvel": "Inova Beauty on your phone",
"O seu estúdio de beleza,<br>à distância de um toque": "Your beauty studio,<br>just a tap away",
"A app vive dentro do site — sem lojas de aplicações, sem downloads. Um clique e abre direto, com marcações, cartão de fidelidade e a sua conta.": "The app lives inside the website — no app stores, no downloads. One click and it opens straight away, with bookings, loyalty card and your account.",
"Tudo o que a app faz por si": "Everything the app does for you",
"📱 A nossa app": "📱 Our app",
"📱 Instalar a APP": "📱 Install the APP",
"▶ Abrir a APP agora": "▶ Open the APP now",
"Abrir a app Inova Beauty": "Open the Inova Beauty app",
"📲 Pôr o ícone no telemóvel (opcional)": "📲 Add the icon to your phone (optional)",
"A app abre direto do site — não precisa de instalar nada. Se quiser o ícone no ecrã do telemóvel (como uma app da loja), use o botão acima ou:": "The app opens straight from the website — nothing to install. If you'd like the icon on your home screen (like a store app), use the button above or:",
"Nova publicação": "New post",
"Escreva uma descrição…": "Write a description…",
"Escreva a sua mensagem…": "Write your message…",
"Inicie sessão para publicar, dar gosto e comentar.": "Log in to post, like and comment.",
"Inicie sessão para ver o seu cartão de selos.": "Log in to see your stamp card.",
"Partilhe o resultado do seu atendimento e veja as publicações de outras clientes. 💛": "Share the result of your appointment and see other clients' posts. 💛",

/* ---------- cartão de fidelidade ---------- */
"Cartão de Fidelidade": "Loyalty card",
"💛 Cartão de Fidelidade": "💛 Loyalty card",
"💛 Os meus selos": "💛 My stamps",
"Cada procedimento vale 1 selo. Ao 10.º selo, ganha um <strong>Threading de Sobrancelhas GRÁTIS</strong>.": "Each procedure is worth 1 stamp. On the 10th stamp you get a <strong>FREE Eyebrow Threading</strong>.",
"Cada procedimento vale 1 selo. Ao 10.º selo: <strong>Threading de Sobrancelhas GRÁTIS</strong>.": "Each procedure is worth 1 stamp. On the 10th stamp: <strong>FREE Eyebrow Threading</strong>.",
"Código do selo (INOVA-S…)": "Stamp code (INOVA-S…)",
"📅 A caderneta é válida de <strong>janeiro a dezembro</strong>. Os selos que não completar até 31/12 recomeçam do zero no ano novo. Recebe o código da Thayana no fim de cada procedimento. ✍️": "📅 The card is valid from <strong>January to December</strong>. Stamps not completed by 31/12 start over in the new year. You get the code from Thayana at the end of each procedure. ✍️",
"📅 Caderneta válida de <strong>janeiro a dezembro</strong>. Os selos não completados recomeçam a 1 de janeiro. O código é entregue pela Thayana no fim de cada procedimento. ✍️": "📅 Card valid from <strong>January to December</strong>. Incomplete stamps reset on 1 January. The code is given by Thayana at the end of each procedure. ✍️",

/* ---------- preçário (títulos e intro; itens ficam em PT) ---------- */
"Preçário oficial": "Official price list",
"Preços transparentes, sempre em euro (€)": "Transparent prices, always in euros (€)",
"Todos os valores em euro (€). Packs especiais assinalados. Marque o seu horário online em 1 minuto.": "All prices in euros (€). Special packages marked. Book online in 1 minute.",
"Threading — Depilação com Linha": "Threading — Thread hair removal",
"Threading — Homem": "Threading — Men",
"Sobrancelhas — Tratamentos": "Eyebrows — Treatments",
"Micropigmentação — Sobrancelhas": "Micropigmentation — Eyebrows",
"Hidraglos — Lábios": "Hidraglos — Lips",
"Lábios — Hidraglos": "Lips — Hidraglos",
"✦ Pack Especial": "✦ Special package",
"✦ Packs Laser": "✦ Laser packages",
"*inclui brow care — hidratação e nutrição": "*includes brow care — hydration and nourishment",
"*inclui lash care — hidratação e nutrição": "*includes lash care — hydration and nourishment",
"Temporariamente indisponível": "Temporarily unavailable",
"Despigmentação": "Depigmentation",

/* ---------- comum ---------- */
"Inova Beauty": "Inova Beauty",
"📍 Localização": "📍 Location",
"🕐 Horário": "🕐 Opening hours",
"💶 Preços": "💶 Prices",
"📅 Marcar horário": "📅 Book an appointment",
"Ver preçário completo": "See full price list",
"Como é feito": "How it's done",
"💬 Chat online": "💬 Live chat",

/* ---------- porquê escolher-nos ---------- */
"Confiança": "Trust",
"Porquê escolher a Inova Beauty": "Why choose Inova Beauty",
"Técnica especializada": "Specialist technique",
"Cada sobrancelha, pestana ou micropigmentação é trabalhada ao detalhe, ao seu rosto — nada de moldes iguais para todas.": "Every brow, lash or micropigmentation is worked in detail, to suit your face — no one-size-fits-all templates.",
"Higiene rigorosa": "Strict hygiene",
"Material esterilizado e descartável a cada cliente. O seu conforto e segurança vêm sempre em primeiro lugar.": "Sterilised and single-use materials for every client. Your comfort and safety always come first.",
"Marcação em 1 minuto": "Book in 1 minute",
"Escolha serviço, dia e hora online e receba a confirmação. Sem filas de mensagens, sem esperas.": "Choose service, day and time online and get your confirmation. No message threads, no waiting.",
"Cartão de fidelidade": "Loyalty card",
"Junte 10 selos e ganhe um serviço grátis. E ainda 10% de desconto na semana do seu aniversário.": "Collect 10 stamps and get a free service. Plus 10% off during your birthday week.",

/* ---------- perguntas frequentes ---------- */
"Dúvidas frequentes": "Frequently asked",
"Perguntas frequentes": "Frequently asked questions",
"Como faço uma marcação?": "How do I book?",
"Quanto tempo demora cada serviço?": "How long does each service take?",
"A depilação a laser é definitiva?": "Is laser hair removal permanent?",
"Posso cancelar ou remarcar?": "Can I cancel or reschedule?",
"Como funciona o cartão de fidelidade?": "How does the loyalty card work?",
"Os meus dados estão seguros?": "Is my data safe?",
"É online e demora cerca de 1 minuto: escolha o serviço, o dia e a hora em": "It's online and takes about 1 minute: choose the service, day and time in",
"e confirme. A sua marcação fica registada diretamente para o estúdio e confirmamos o horário em breve.": "and confirm. Your booking goes straight to the studio and we confirm the time shortly.",
"Política de Privacidade": "Privacy Policy",
"Depende do serviço: o threading de sobrancelhas é rápido (cerca de 15 minutos), tratamentos de pestanas e coloração rondam os 30–60 minutos, e a depilação a laser varia entre 15 e 60 minutos conforme a zona. Indicamos sempre a duração ao confirmar.": "It depends on the service: eyebrow threading is quick (around 15 minutes), lash treatments and tinting take about 30–60 minutes, and laser hair removal ranges from 15 to 60 minutes depending on the area. We always tell you the duration when confirming.",
"Não prometemos resultado \"definitivo\". O laser proporciona uma redução progressiva e duradoura do pelo ao longo das sessões — em média são precisas 6 a 10 sessões, com intervalos de 4 a 6 semanas.": "We don't promise a \"permanent\" result. Laser gives a progressive, long-lasting reduction of hair over the sessions — on average 6 to 10 sessions are needed, 4 to 6 weeks apart.",
"Claro. Se precisar de alterar ou cancelar, avise-nos com antecedência pelo": "Of course. If you need to change or cancel, let us know in advance via",
"para libertarmos o horário para outra cliente.": "so we can free up the slot for another client.",
"Ao criar a sua conta gratuita, junta selos a cada visita. Com 10 selos ganha um serviço grátis. E recebe automaticamente um cupão de 10% de desconto na semana do seu aniversário. 🎂": "When you create your free account, you collect stamps on every visit. With 10 stamps you get a free service. And you automatically receive a 10% discount coupon during your birthday week. 🎂",
"Sim. Tratamos os seus dados ao abrigo do RGPD e não os vendemos nem cedemos a terceiros. Saiba mais na nossa": "Yes. We process your data under the GDPR and never sell or share it with third parties. Learn more in our"

};
