/* ============================================================
   INOVA BEAUTY — Español
   Chave = frase em português (como está no site). Valor = tradução.
   O que não estiver aqui fica em português (nunca inventa).
   ============================================================ */
window.INOVA_DIC = window.INOVA_DIC || {};
window.INOVA_DIC.es = {

/* ---------- navegação / rodapé ---------- */
"Home": "Inicio",
"Serviços": "Servicios",
"Preçário": "Precios",
"Processos": "Cómo se hace",
"Sobre": "Nosotras",
"Sobre nós": "Sobre nosotras",
"Contato": "Contacto",
"Localização": "Ubicación",
"Navegação": "Navegación",
"Navegação principal": "Navegación principal",
"Navegação da app": "Navegación de la app",
"Navegação dos destaques": "Navegación de destacados",
"Contactos": "Contactos",
"Clientes": "Clientas",
"Área reservada": "Área reservada",
"Todos os serviços →": "Todos los servicios →",
"Ver todos os serviços": "Ver todos los servicios",
"Ver site completo": "Ver sitio completo",
"© 2026 Inova Beauty — Todos os direitos reservados. ·": "© 2026 Inova Beauty — Todos los derechos reservados. ·",
"Beleza, precisão e cuidado em cada detalhe.": "Belleza, precisión y cuidado en cada detalle.",
"Beleza, precisão e cuidado.": "Belleza, precisión y cuidado.",
"Beleza, precisão e cuidado em cada detalhe. Especialistas em sobrancelhas, pestanas e micropigmentação. Em Canidelo, Vila Nova de Gaia.": "Belleza, precisión y cuidado en cada detalle. Especialistas en cejas, pestañas y micropigmentación. En Canidelo, Vila Nova de Gaia.",

/* ---------- ubicación ---------- */
"Zona": "Zona",
"Atendemos em Canidelo, Vila Nova de Gaia — na Rua da Bélgica, mesmo em frente à Padaria Mirassol. O atendimento é por marcação e a morada exata é enviada assim que confirma o seu horário.": "Atendemos en Canidelo, Vila Nova de Gaia — en la Rua da Bélgica, justo enfrente de la Padaria Mirassol. Atendemos con cita previa y enviamos la dirección exacta en cuanto confirmas tu reserva.",
"Canidelo, Vila Nova de Gaia — Rua da Bélgica, mesmo em frente à <strong>Padaria Mirassol</strong>. Espaço reservado, por marcação. A morada exata é enviada ao confirmar.": "Canidelo, Vila Nova de Gaia — Rua da Bélgica, justo enfrente de la <strong>Padaria Mirassol</strong>. Un espacio reservado, con cita previa. La dirección exacta se envía al confirmar.",
"✨ Marcar e receber a morada": "✨ Reservar y recibir la dirección",
"Referência: <strong>Padaria Mirassol</strong>, na Rua da Bélgica (Canidelo). Estamos mesmo em frente. A morada exata é reservada e enviada ao confirmar a marcação.": "Referencia: <strong>Padaria Mirassol</strong>, en la Rua da Bélgica (Canidelo). Estamos justo enfrente. La dirección exacta es reservada y se envía al confirmar la reserva.",

/* ---------- botões / ações ---------- */
"Agendar": "Reservar",
"Marcar horário": "Reservar cita",
"Marcar horário online": "Reservar online",
"Marcação online": "Reserva online",
"✨ Marcar horário": "✨ Reservar cita",
"✨ Marcar horário online": "✨ Reservar online",
"✨ Fazer marcação online": "✨ Reservar online",
"✨ Marcar este serviço": "✨ Reservar este servicio",
"✨ Confirmar marcação": "✨ Confirmar reserva",
"Fazer marcação": "Reservar",
"Confirmar marcação": "Confirmar reserva",
"Entrar": "Entrar",
"Iniciar sessão": "Iniciar sesión",
"Entrar / Registar-se": "Entrar / Registrarse",
"👤 Entrar": "👤 Entrar",
"Registar-se": "Registrarse",
"Criar conta": "Crear cuenta",
"Criar a minha conta": "Crear mi cuenta",
"ainda não tem conta?": "¿aún no tienes cuenta?",
"Já tem conta? Iniciar sessão": "¿Ya tienes cuenta? Inicia sesión",
"Sair": "Salir",
"Guardar": "Guardar",
"Guardar alterações": "Guardar cambios",
"Adicionar": "Añadir",
"Adicionar selo": "Añadir sello",
"Enviar": "Enviar",
"Enviar foto": "Enviar foto",
"Publicar": "Publicar",
"Remover": "Quitar",
"Trocar foto": "Cambiar foto",
"📷 Escolher foto": "📷 Elegir foto",
"Escolher personagem": "Elegir personaje",
"Apagar conta": "Eliminar cuenta",
"Alterar senha": "Cambiar contraseña",
"Alterar senha (por email)": "Cambiar contraseña (por email)",
"Esqueci a minha senha": "Olvidé mi contraseña",
"Explorar": "Explorar",
"Saber mais": "Saber más",
"Ver detalhes": "Ver detalles",
"Ver preços": "Ver precios",
"Ver preços deste serviço": "Ver precios de este servicio",
"Ver preço no preçário": "Ver precio en la lista",
"Ver preçário completo": "Ver lista de precios completa",
"Ver serviços": "Ver servicios",
"Ver como é feito": "Ver cómo se hace",
"Ver passo a passo": "Ver paso a paso",
"Conhecer o serviço": "Descubrir el servicio",
"Conhecer a Inova Beauty": "Descubrir Inova Beauty",
"Toque para abrir": "Toca para abrir",
"Fechar chat": "Cerrar chat",
"Abrir chat online": "Abrir chat en vivo",
"Abrir menu": "Abrir menú",
"Pedir localização": "Pedir ubicación",
"Usar o meu prémio nesta marcação": "Usar mi premio en esta reserva",

/* ---------- home / hero ---------- */
"Marcação online": "Reserva online",
"Marque o seu horário <em>online</em>, em 1 minuto": "Reserva tu cita <em>online</em>, en 1 minuto",
"Escolha o serviço, o dia e a hora e confirme — sem telefonemas, sem esperas. É a forma mais rápida e organizada de garantir a sua vaga.": "Elige el servicio, el día y la hora y confirma — sin llamadas, sin esperas. Es la forma más rápida y organizada de asegurar tu cita.",
"Rápido · Sem esperas · Escolha o seu horário": "Rápido · Sin esperas · Elige tu horario",
"Tem alguma dúvida? Fale connosco no WhatsApp →": "¿Tienes alguna duda? Escríbenos por WhatsApp →",
"Tem dúvidas? Fale connosco no WhatsApp →": "¿Dudas? Escríbenos por WhatsApp →",
"Sobrancelhas perfeitas <em>ao acordar</em>": "Cejas perfectas <em>al despertar</em>",
"Técnica fio a fio ultra natural, com consulta de avaliação deduzida no valor do procedimento. Veja o passo a passo sem mistérios.": "Técnica pelo a pelo ultra natural, con la consulta de evaluación descontada del precio del procedimiento. Mira el paso a paso sin misterios.",
"🎂 Presente de aniversário": "🎂 Regalo de cumpleaños",
"10% de desconto no seu <em>aniversário</em>": "10% de descuento en tu <em>cumpleaños</em>",
"Crie a sua conta gratuita e receba automaticamente um cupom de 10% na semana do seu aniversário. É o nosso mimo para si.": "Crea tu cuenta gratuita y recibe automáticamente un cupón del 10% en la semana de tu cumpleaños. Es nuestro detalle para ti.",
"Beleza, precisão e <em>cuidado</em> em cada detalhe": "Belleza, precisión y <em>cuidado</em> en cada detalle",
"Especialistas em sobrancelhas, pestanas, micropigmentação e depilação com linha. Realce a sua beleza natural com quem trata cada detalhe como arte.": "Especialistas en cejas, pestañas, micropigmentación y depilación con hilo. Realza tu belleza natural con quien trata cada detalle como arte.",
"Destaques Inova Beauty": "Destacados Inova Beauty",
"Slide anterior": "Diapositiva anterior",
"Slide seguinte": "Diapositiva siguiente",
"Ir para o slide 1": "Ir a la diapositiva 1",
"Ir para o slide 2": "Ir a la diapositiva 2",
"Ir para o slide 3": "Ir a la diapositiva 3",
"Ir para o slide 4": "Ir a la diapositiva 4",

/* ---------- home / secções ---------- */
"O seu rosto merece um olhar de especialista": "Tu rostro merece la mirada de una experta",
"Na Inova Beauty unimos técnica, visagismo e produtos de excelência para realçar o que a natureza lhe deu. Cada atendimento é personalizado — porque não há dois rostos iguais.": "En Inova Beauty unimos técnica, visagismo y productos de excelencia para realzar lo que la naturaleza te dio. Cada cita es personalizada — porque no hay dos rostros iguales.",
"Profissionais especializadas e certificadas": "Profesionales especializadas y certificadas",
"Técnicas atuais: threading, laminação, lifting e micropigmentação": "Técnicas actuales: threading, laminado, lifting y micropigmentación",
"Ambiente acolhedor, higiene e produtos premium": "Ambiente acogedor, higiene y productos premium",
"O que fazemos por si": "Lo que hacemos por ti",
"Design com linha, laminação, coloração e tratamentos de nutrição para umas sobrancelhas perfeitas.": "Diseño con hilo, laminado, coloración y tratamientos de nutrición para unas cejas perfectas.",
"Lifting, permanente e tintura para um olhar marcante todos os dias, sem esforço.": "Lifting, permanente y tinte para una mirada marcada todos los días, sin esfuerzo.",
"Micropigmentação de sobrancelhas fio a fio, com resultado natural e duradouro.": "Micropigmentación de cejas pelo a pelo, con un resultado natural y duradero.",
"Hidratação profunda e brilho para os lábios, com ou sem cor — lábios nutridos, macios e luminosos.": "Hidratación profunda y brillo para los labios, con o sin color — labios nutridos, suaves y luminosos.",
"Depilação com linha para rosto e sobrancelhas — precisão total, sem químicos e ideal para peles sensíveis.": "Depilación con hilo para rostro y cejas — precisión total, sin químicos e ideal para pieles sensibles.",
"Depilação a laser para rosto e corpo, com resultados progressivos e duradouros.": "Depilación láser para rostro y cuerpo, con resultados progresivos y duraderos.",
"Preços claros, sem surpresas": "Precios claros, sin sorpresas",
"Consulte o preçário completo com todos os serviços e packs especiais — valores em euro (€).": "Consulta la lista completa con todos los servicios y packs especiales — precios en euros (€).",
"Pronta para realçar a sua beleza?": "¿Lista para realzar tu belleza?",
"Marque o seu horário online em 1 minuto — escolha o serviço, o dia e a hora. Sem telefonemas, sem esperas.": "Reserva tu cita online en 1 minuto — elige el servicio, el día y la hora. Sin llamadas, sin esperas.",

/* ---------- serviços ---------- */
"Os nossos serviços": "Nuestros servicios",
"Toque na imagem de cada serviço para ver as opções disponíveis — e clique para conhecer os detalhes e preços.": "Toca la imagen de cada servicio para ver las opciones disponibles — y haz clic para ver los detalles y precios.",
"Sobrancelhas": "Cejas",
"Pestanas": "Pestañas",
"Micropigmentação": "Micropigmentación",
"Lábios": "Labios",
"Lábios (Hidraglos)": "Labios (Hidraglos)",
"Threading": "Threading",
"Depilação a Laser": "Depilación láser",
"Toque para abrir": "Toca para abrir",
"Ver preços": "Ver precios",
"Ver tudo em Sobrancelhas": "Ver todo en Cejas",
"Ver tudo em Pestanas": "Ver todo en Pestañas",
"Ver tudo em Micropigmentação": "Ver todo en Micropigmentación",
"Ver tudo em Lábios": "Ver todo en Labios",
"Mostrar sub-serviços de Sobrancelhas": "Mostrar subservicios de Cejas",
"Mostrar sub-serviços de Pestanas": "Mostrar subservicios de Pestañas",
"Mostrar sub-serviços de Micropigmentação": "Mostrar subservicios de Micropigmentación",
"Mostrar sub-serviços de Lábios": "Mostrar subservicios de Labios",
"Alisamento": "Alisado",
"Alisamento de Sobrancelhas": "Alisado de cejas",
"Brow Lamination": "Brow Lamination",
"Coloração": "Coloración",
"Coloração de Sobrancelhas": "Coloración de cejas",
"Coloração de Sobrancelhas (Henna / Tintura / Descoloração)": "Coloración de cejas (Henna / Tinte / Decoloración)",
"Lifting de Pestanas": "Lifting de pestañas",
"Lifting + Tintura de Pestanas": "Lifting + Tinte de pestañas",
"Permanente de Pestanas": "Permanente de pestañas",
"Tintura de Pestanas": "Tinte de pestañas",
"Extensão de Pestanas": "Extensiones de pestañas",
"Micropigmentação de Sobrancelhas": "Micropigmentación de cejas",
"Micro de Sobrancelhas": "Micro de cejas",
"Hidraglos": "Hidraglos",
"Hidraglos de Lábios": "Hidraglos de labios",
"Threading de Sobrancelhas": "Threading de cejas",
"Threading (rosto)": "Threading (rostro)",
"Threading (Depilação com Linha)": "Threading (depilación con hilo)",
"Teen (até 18 anos)": "Teen (hasta 18 años)",
"Tratamentos": "Tratamientos",
"Produtos": "Productos",
"Outro (indico na mensagem)": "Otro (lo indico en el mensaje)",

/* ---------- página de serviço ---------- */
"Benefícios": "Beneficios",
"Para quem é": "Para quién es",
"Vantagens": "Ventajas",
"Preço": "Precio",
"Preços": "Precios",
"A magia da linha": "La magia del hilo",
"Definição fio a fio": "Definición pelo a pelo",
"O threading é a técnica de depilação com linha que permite desenhar as sobrancelhas fio a fio, com uma precisão que a cera e a pinça não conseguem igualar.": "El threading es la técnica de depilación con hilo que permite diseñar las cejas pelo a pelo, con una precisión que la cera y las pinzas no logran igualar.",
"Desenho preciso e simétrico, adaptado ao seu rosto": "Diseño preciso y simétrico, adaptado a tu rostro",
"Sem químicos nem produtos agressivos": "Sin químicos ni productos agresivos",
"Ideal para peles sensíveis e com tendência a irritação": "Ideal para pieles sensibles y con tendencia a irritarse",
"Resultado mais duradouro do que a pinça": "Resultado más duradero que las pinzas",
"Para quem quer sobrancelhas definidas com um acabamento impecável — incluindo peles sensíveis, reativas ou em tratamento dermatológico.": "Para quien quiere cejas definidas con un acabado impecable — incluyendo pieles sensibles, reactivas o en tratamiento dermatológico.",
"A laminação de sobrancelhas realinha e fixa os pelos na direção ideal, criando um efeito cheio, penteado e uniforme que dura semanas.": "El laminado de cejas realinea y fija los pelos en la dirección ideal, creando un efecto lleno, peinado y uniforme que dura semanas.",
"A curvatura das suas pestanas naturais elevada desde a raiz — efeito de máscara e olhar aberto, sem extensões.": "La curvatura de tus pestañas naturales elevada desde la raíz — efecto de máscara y mirada abierta, sin extensiones.",
"A coloração dá cor, preenchimento e definição às sobrancelhas — da henna (que também pigmenta a pele) à tintura dos pelos e à descoloração para clarear e uniformizar.": "La coloración da color, relleno y definición a las cejas — desde la henna (que también pigmenta la piel) hasta el tinte del pelo y la decoloración para aclarar y uniformar.",
"O alisamento disciplina pelos rebeldes ou encaracolados, deixando as sobrancelhas alinhadas, suaves e fáceis de manter.": "El alisado disciplina pelos rebeldes o rizados, dejando las cejas alineadas, suaves y fáciles de mantener.",
"Pigmentos semi-permanentes desenhados fio a fio com dermógrafo, corrigindo falhas com um resultado ultra natural.": "Pigmentos semipermanentes diseñados pelo a pelo con dermógrafo, corrigiendo huecos con un resultado ultra natural.",
"Fios aplicados um a um sobre as suas pestanas naturais, criando comprimento, curvatura e volume à sua medida.": "Pestañas aplicadas una a una sobre tus pestañas naturales, creando longitud, curvatura y volumen a tu medida.",
"Tratamento de hidratação Hidraglos para lábios nutridos, macios e luminosos — com ou sem cor.": "Tratamiento de hidratación Hidraglos para labios nutridos, suaves y luminosos — con o sin color.",
"Luz concentrada que atinge a raiz do pelo, reduzindo o crescimento sessão após sessão — resultados progressivos e duradouros.": "Luz concentrada que alcanza la raíz del pelo, reduciendo el crecimiento sesión tras sesión — resultados progresivos y duraderos.",
"O tratamento que disciplina e realinha os pelos das sobrancelhas, criando o efeito cheio e penteado que dura semanas.": "El tratamiento que disciplina y realinea los pelos de las cejas, creando el efecto lleno y peinado que dura semanas.",
"Henna, tintura ou descoloração para dar cor, preenchimento e uniformidade às sobrancelhas com efeito natural.": "Henna, tinte o decoloración para dar color, relleno y uniformidad a las cejas con efecto natural.",
"Uma técnica milenar que usa apenas uma linha de algodão torcida para remover os pelos pela raiz, com precisão fio a fio.": "Una técnica milenaria que usa solo un hilo de algodón torcido para quitar los pelos de raíz, con precisión pelo a pelo.",
"Ficou com vontade de experimentar?": "¿Te dieron ganas de probarlo?",
"Fale connosco no WhatsApp — esclarecemos qualquer dúvida antes de marcar.": "Escríbenos por WhatsApp — resolvemos cualquier duda antes de reservar.",
"Encontrou o serviço ideal?": "¿Encontraste el servicio ideal?",
"Marque o seu horário online em 1 minuto e garanta já a sua vaga.": "Reserva online en 1 minuto y asegura tu cita ya.",
"Marcação online em 1 minuto.": "Reserva online en 1 minuto.",
"Dúvidas? WhatsApp": "¿Dudas? WhatsApp",

/* ---------- processos ---------- */
"Como é feito": "Cómo se hace",
"Como é feito cada procedimento": "Cómo se hace cada procedimiento",
"Saber o que esperar é o primeiro passo para relaxar. Escolha um procedimento e veja o passo a passo completo.": "Saber qué esperar es el primer paso para relajarse. Elige un procedimiento y mira el paso a paso completo.",
"Passo a passo": "Paso a paso",
"Sem mistérios": "Sin misterios",
"Cuidados depois do procedimento": "Cuidados después del procedimiento",
"Preparação da pele": "Preparación de la piel",
"Avaliação e desenho": "Evaluación y diseño",
"Finalização": "Finalización",
"Limpeza suave da zona para remover oleosidade e maquilhagem, garantindo higiene e conforto.": "Limpieza suave de la zona para quitar grasa y maquillaje, garantizando higiene y confort.",
"Analisamos o formato do seu rosto e desenhamos a linha ideal das sobrancelhas, respeitando a sua simetria natural.": "Analizamos la forma de tu rostro y diseñamos la línea ideal de las cejas, respetando tu simetría natural.",
"Refinamos o desenho pelo a pelo até o contorno ficar perfeito e simétrico.": "Refinamos el diseño pelo a pelo hasta que el contorno queda perfecto y simétrico.",
"Aplicamos gel calmante e penteamos as sobrancelhas, mostrando o resultado ao espelho.": "Aplicamos gel calmante y peinamos las cejas, mostrando el resultado en el espejo.",
"Hidrate a pele com um produto suave": "Hidrata la piel con un producto suave",
"Evite calor intenso, vapor e sol direto nas primeiras 24 horas": "Evita el calor intenso, el vapor y el sol directo las primeras 24 horas",
"Não aplique maquilhagem na zona no próprio dia": "No apliques maquillaje en la zona el mismo día",
"🕐 Duração média: ≈ 15–20 min": "🕐 Duración media: ≈ 15–20 min",
"🕐 Duração média: ≈ 15–20 minutos": "🕐 Duración media: ≈ 15–20 minutos",

/* ---------- sobre ---------- */
"A nossa história": "Nuestra historia",
"Mais do que estética, autoestima": "Más que estética, autoestima",
"Por trás da Inova Beauty está a <strong>Thayana</strong> — apaixonada por realçar a beleza natural de cada pessoa. Especializada nas técnicas mais atuais de embelezamento do olhar — threading, laminação de sobrancelhas, lifting de pestanas e micropigmentação — entrega resultados precisos, naturais e duradouros.": "Detrás de Inova Beauty está <strong>Thayana</strong> — apasionada por realzar la belleza natural de cada persona. Especializada en las técnicas más actuales de embellecimiento de la mirada — threading, laminado de cejas, lifting de pestañas y micropigmentación — entrega resultados precisos, naturales y duraderos.",
"Cada cliente é única. Por isso, todos os nossos serviços começam com uma avaliação personalizada do seu rosto, tom de pele e estilo — para que o resultado seja perfeito para si.": "Cada clienta es única. Por eso, todos nuestros servicios comienzan con una evaluación personalizada de tu rostro, tono de piel y estilo — para que el resultado sea perfecto para ti.",
"Atendimento personalizado e sem pressas": "Atención personalizada y sin prisas",
"Higiene rigorosa e produtos de qualidade premium": "Higiene rigurosa y productos de calidad premium",
"Formação contínua nas técnicas mais recentes": "Formación continua en las técnicas más recientes",
"Venha conhecer-nos": "Ven a conocernos",
"Marque a sua visita online — escolha o dia e a hora em 1 minuto. Teremos todo o gosto em recebê-la.": "Reserva tu visita online — elige el día y la hora en 1 minuto. Será un placer recibirte.",

/* ---------- contato / localização ---------- */
"Fale connosco": "Contáctanos",
"A forma mais rápida de marcar é online, em 1 minuto. O WhatsApp fica para tirar dúvidas — respondemos rapidamente.": "La forma más rápida de reservar es online, en 1 minuto. El WhatsApp es para dudas — respondemos rápido.",
"A forma mais rápida — escolha serviço, dia e hora em 1 minuto.": "La forma más rápida — elige servicio, día y hora en 1 minuto.",
"Telefone": "Teléfono",
"Prefere ligar? Estamos disponíveis no horário de funcionamento.": "¿Prefieres llamar? Estamos disponibles en el horario de atención.",
"Horário": "Horario",
"Segunda a Sábado<br>09h00 – 19h00": "Lunes a Sábado<br>09:00 – 19:00",
"Marcações": "Reservas",
"Atendemos por marcação para lhe garantir um serviço sem esperas.": "Atendemos con cita previa para garantizarte un servicio sin esperas.",
"Pronta para marcar?": "¿Lista para reservar?",
"Marque o seu horário online em 1 minuto. Se tiver dúvidas, fale connosco no WhatsApp.": "Reserva online en 1 minuto. Si tienes dudas, escríbenos por WhatsApp.",
"Onde estamos": "Dónde estamos",
"Onde encontrar a Inova Beauty": "Dónde encontrar Inova Beauty",
"Morada": "Dirección",
"Estamos à sua espera num espaço pensado para o seu conforto.": "Te esperamos en un espacio pensado para tu comodidad.",
"Envie-nos mensagem no WhatsApp e partilhamos de imediato a localização exata do estúdio.": "Escríbenos por WhatsApp y compartimos al momento la ubicación exacta del estudio.",
"Venha visitar-nos": "Ven a visitarnos",
"Marque o seu horário e receba a localização exata na hora.": "Reserva tu cita y recibe la ubicación exacta al momento.",
"Dúvidas no WhatsApp: +351 919 277 205": "Dudas por WhatsApp: +351 919 277 205",
"Telefone: +351 919 277 205": "Teléfono: +351 919 277 205",
"Tirar dúvidas no WhatsApp": "Resolver dudas por WhatsApp",
"Dúvidas? Fale connosco": "¿Dudas? Contáctanos",
"Dúvidas?": "¿Dudas?",
"● Online — respondemos já": "● En línea — respondemos ya",

/* ---------- marcação (agendar) ---------- */
"Agendamento": "Reserva",
"Preencha os dados e confirme — a sua marcação fica registada e confirmamos o seu horário em breve.": "Rellena los datos y confirma — tu reserva queda registrada y confirmamos tu hora en breve.",
"Nome": "Nombre",
"Nome*": "Nombre*",
"O seu nome": "Tu nombre",
"Telemóvel": "Móvil",
"Telemóvel*": "Móvil*",
"Telemóvel* (obrigatório)": "Móvil* (obligatorio)",
"Serviço*": "Servicio*",
"Serviço (opcional)": "Servicio (opcional)",
"Dia preferido*": "Día preferido*",
"Hora preferida*": "Hora preferida*",
"Hora preferida* (30 em 30 min)": "Hora preferida* (cada 30 min)",
"Cupom (opcional)": "Cupón (opcional)",
"Cupom de desconto (opcional)": "Cupón de descuento (opcional)",
"Observações (opcional)": "Observaciones (opcional)",
"Alguma informação que devamos saber?": "¿Algo que debamos saber?",
"A sua marcação fica registada diretamente para o estúdio. Confirmamos o seu horário em breve.": "Tu reserva queda registrada directamente en el estudio. Confirmamos tu hora en breve.",
"Escolha o serviço, o dia e a hora — a marcação fica registada e confirmamos em minutos.": "Elige el servicio, el día y la hora — la reserva queda registrada y confirmamos en minutos.",
"🎁 Tem um prémio para usar!": "🎁 ¡Tienes un premio para usar!",
"Sobrancelha Grátis": "Cejas gratis",
"Ganhou por completar 10 selos. Marque este serviço e não paga nada.": "Lo ganaste por completar 10 sellos. Reserva este servicio y no pagas nada.",

/* ---------- conta ---------- */
"A minha conta": "Mi cuenta",
"Email": "Email",
"Email*": "Email*",
"Senha": "Contraseña",
"A sua senha": "Tu contraseña",
"Senha* (mín. 6 caracteres)": "Contraseña* (mín. 6 caracteres)",
"Senha* (mín. 6)": "Contraseña* (mín. 6)",
"Confirmar senha*": "Confirmar contraseña*",
"Data de nascimento*": "Fecha de nacimiento*",
"Data de nascimento* (obrigatória)": "Fecha de nacimiento* (obligatoria)",
"Sexo": "Sexo",
"Sexo*": "Sexo*",
"Masculino": "Masculino",
"Feminino": "Femenino",
"Foto de perfil (opcional)": "Foto de perfil (opcional)",
"Ou usamos um ícone": "O usamos un icono",
"1 conta por número — evita duplicados.": "1 cuenta por número — evita duplicados.",
"1 conta por número.": "1 cuenta por número.",
"Para o seu cupom de aniversário 🎁": "Para tu cupón de cumpleaños 🎁",
"Para receber o seu voucher de aniversário 🎁": "Para recibir tu vale de cumpleaños 🎁",
"⚙️ Configurações da conta": "⚙️ Ajustes de la cuenta",
"🔒 A sua senha é protegida com criptografia (SHA-256 + salt) e os dados ficam guardados apenas neste dispositivo — nunca são enviados para terceiros.": "🔒 Tu contraseña está protegida con cifrado (SHA-256 + salt) y los datos se guardan solo en este dispositivo — nunca se envían a terceros.",
"🔒 Senha protegida com criptografia (SHA-256 + salt), guardada só neste dispositivo.": "🔒 Contraseña protegida con cifrado (SHA-256 + salt), guardada solo en este dispositivo.",

/* ---------- app ---------- */
"Início": "Inicio",
"Marcar": "Reservar",
"Feed": "Feed",
"Cartão": "Tarjeta",
"Conta": "Cuenta",
"Cartão de selos": "Tarjeta de sellos",
"WhatsApp": "WhatsApp",
"Comunidade": "Comunidad",
"Comunidade Inova": "Comunidad Inova",
"Olá!": "¡Hola!",
"Olá! 👋": "¡Hola! 👋",
"Bem-vinda à Inova Beauty.": "Bienvenida a Inova Beauty.",
"Beleza, precisão e cuidado.": "Belleza, precisión y cuidado.",
"Inova Beauty no seu telemóvel": "Inova Beauty en tu móvil",
"O seu estúdio de beleza,<br>à distância de um toque": "Tu estudio de belleza,<br>a un toque de distancia",
"A app vive dentro do site — sem lojas de aplicações, sem downloads. Um clique e abre direto, com marcações, cartão de fidelidade e a sua conta.": "La app vive dentro del sitio — sin tiendas de apps, sin descargas. Un clic y se abre al instante, con reservas, tarjeta de fidelidad y tu cuenta.",
"Tudo o que a app faz por si": "Todo lo que la app hace por ti",
"📱 A nossa app": "📱 Nuestra app",
"📱 Instalar a APP": "📱 Instalar la APP",
"▶ Abrir a APP agora": "▶ Abrir la APP ahora",
"Abrir a app Inova Beauty": "Abrir la app Inova Beauty",
"📲 Pôr o ícone no telemóvel (opcional)": "📲 Poner el icono en el móvil (opcional)",
"A app abre direto do site — não precisa de instalar nada. Se quiser o ícone no ecrã do telemóvel (como uma app da loja), use o botão acima ou:": "La app se abre directo del sitio — no hace falta instalar nada. Si quieres el icono en la pantalla del móvil (como una app de tienda), usa el botón de arriba o:",
"Nova publicação": "Nueva publicación",
"Escreva uma descrição…": "Escribe una descripción…",
"Escreva a sua mensagem…": "Escribe tu mensaje…",
"Inicie sessão para publicar, dar gosto e comentar.": "Inicia sesión para publicar, dar me gusta y comentar.",
"Inicie sessão para ver o seu cartão de selos.": "Inicia sesión para ver tu tarjeta de sellos.",
"Partilhe o resultado do seu atendimento e veja as publicações de outras clientes. 💛": "Comparte el resultado de tu cita y mira las publicaciones de otras clientas. 💛",

/* ---------- cartão de fidelidade ---------- */
"Cartão de Fidelidade": "Tarjeta de fidelidad",
"💛 Cartão de Fidelidade": "💛 Tarjeta de fidelidad",
"💛 Os meus selos": "💛 Mis sellos",
"Cada procedimento vale 1 selo. Ao 10.º selo, ganha um <strong>Threading de Sobrancelhas GRÁTIS</strong>.": "Cada procedimiento vale 1 sello. Al 10.º sello, ganas un <strong>Threading de Cejas GRATIS</strong>.",
"Cada procedimento vale 1 selo. Ao 10.º selo: <strong>Threading de Sobrancelhas GRÁTIS</strong>.": "Cada procedimiento vale 1 sello. Al 10.º sello: <strong>Threading de Cejas GRATIS</strong>.",
"Código do selo (INOVA-S…)": "Código del sello (INOVA-S…)",
"📅 A caderneta é válida de <strong>janeiro a dezembro</strong>. Os selos que não completar até 31/12 recomeçam do zero no ano novo. Recebe o código da Thayana no fim de cada procedimento. ✍️": "📅 La cartilla es válida de <strong>enero a diciembre</strong>. Los sellos que no completes antes del 31/12 vuelven a cero en el año nuevo. Recibes el código de Thayana al final de cada procedimiento. ✍️",
"📅 Caderneta válida de <strong>janeiro a dezembro</strong>. Os selos não completados recomeçam a 1 de janeiro. O código é entregue pela Thayana no fim de cada procedimento. ✍️": "📅 Cartilla válida de <strong>enero a diciembre</strong>. Los sellos no completados vuelven a empezar el 1 de enero. El código lo entrega Thayana al final de cada procedimiento. ✍️",

/* ---------- preçário (títulos e intro; itens ficam em PT) ---------- */
"Preçário oficial": "Lista de precios oficial",
"Preços transparentes, sempre em euro (€)": "Precios transparentes, siempre en euros (€)",
"Todos os valores em euro (€). Packs especiais assinalados. Marque o seu horário online em 1 minuto.": "Todos los precios en euros (€). Packs especiales señalados. Reserva online en 1 minuto.",
"Threading — Depilação com Linha": "Threading — Depilación con hilo",
"Threading — Homem": "Threading — Hombre",
"Sobrancelhas — Tratamentos": "Cejas — Tratamientos",
"Micropigmentação — Sobrancelhas": "Micropigmentación — Cejas",
"Hidraglos — Lábios": "Hidraglos — Labios",
"Lábios — Hidraglos": "Labios — Hidraglos",
"✦ Pack Especial": "✦ Pack especial",
"✦ Packs Laser": "✦ Packs láser",
"*inclui brow care — hidratação e nutrição": "*incluye brow care — hidratación y nutrición",
"*inclui lash care — hidratação e nutrição": "*incluye lash care — hidratación y nutrición",
"Temporariamente indisponível": "Temporalmente no disponible",
"Despigmentação": "Despigmentación",

/* ---------- comum ---------- */
"Inova Beauty": "Inova Beauty",
"📍 Localização": "📍 Ubicación",
"🕐 Horário": "🕐 Horario",
"💶 Preços": "💶 Precios",
"📅 Marcar horário": "📅 Reservar cita",
"Ver preçário completo": "Ver lista de precios completa",
"💬 Chat online": "💬 Chat en vivo",

/* ---------- por qué elegirnos ---------- */
"Confiança": "Confianza",
"Porquê escolher a Inova Beauty": "Por qué elegir Inova Beauty",
"Técnica especializada": "Técnica especializada",
"Cada sobrancelha, pestana ou micropigmentação é trabalhada ao detalhe, ao seu rosto — nada de moldes iguais para todas.": "Cada ceja, pestaña o micropigmentación se trabaja al detalle, para tu rostro — nada de moldes iguales para todas.",
"Higiene rigorosa": "Higiene rigurosa",
"Material esterilizado e descartável a cada cliente. O seu conforto e segurança vêm sempre em primeiro lugar.": "Material esterilizado y desechable con cada cliente. Tu comodidad y seguridad son siempre lo primero.",
"Marcação em 1 minuto": "Reserva en 1 minuto",
"Escolha serviço, dia e hora online e receba a confirmação. Sem filas de mensagens, sem esperas.": "Elige servicio, día y hora online y recibe la confirmación. Sin cadenas de mensajes, sin esperas.",
"Cartão de fidelidade": "Tarjeta de fidelidad",
"Junte 10 selos e ganhe um serviço grátis. E ainda 10% de desconto na semana do seu aniversário.": "Junta 10 sellos y consigue un servicio gratis. Y además un 10% de descuento en la semana de tu cumpleaños.",

/* ---------- preguntas frecuentes ---------- */
"Dúvidas frequentes": "Preguntas frecuentes",
"Perguntas frequentes": "Preguntas frecuentes",
"Como faço uma marcação?": "¿Cómo hago una reserva?",
"Quanto tempo demora cada serviço?": "¿Cuánto dura cada servicio?",
"A depilação a laser é definitiva?": "¿La depilación láser es definitiva?",
"Posso cancelar ou remarcar?": "¿Puedo cancelar o cambiar la cita?",
"Como funciona o cartão de fidelidade?": "¿Cómo funciona la tarjeta de fidelidad?",
"Os meus dados estão seguros?": "¿Mis datos están seguros?",
"É online e demora cerca de 1 minuto: escolha o serviço, o dia e a hora em": "Es online y tarda alrededor de 1 minuto: elige el servicio, el día y la hora en",
"e confirme. A sua marcação fica registada diretamente para o estúdio e confirmamos o horário em breve.": "y confirma. Tu reserva queda registrada directamente para el estudio y confirmamos el horario en breve.",
"Política de Privacidade": "Política de Privacidad",
"Depende do serviço: o threading de sobrancelhas é rápido (cerca de 15 minutos), tratamentos de pestanas e coloração rondam os 30–60 minutos, e a depilação a laser varia entre 15 e 60 minutos conforme a zona. Indicamos sempre a duração ao confirmar.": "Depende del servicio: el threading de cejas es rápido (unos 15 minutos), los tratamientos de pestañas y coloración rondan los 30–60 minutos, y la depilación láser varía entre 15 y 60 minutos según la zona. Siempre indicamos la duración al confirmar.",
"Não prometemos resultado \"definitivo\". O laser proporciona uma redução progressiva e duradoura do pelo ao longo das sessões — em média são precisas 6 a 10 sessões, com intervalos de 4 a 6 semanas.": "No prometemos un resultado \"definitivo\". El láser ofrece una reducción progresiva y duradera del vello a lo largo de las sesiones — de media hacen falta de 6 a 10 sesiones, con intervalos de 4 a 6 semanas.",
"Claro. Se precisar de alterar ou cancelar, avise-nos com antecedência pelo": "Claro. Si necesitas cambiar o cancelar, avísanos con antelación por",
"para libertarmos o horário para outra cliente.": "para liberar el horario para otra clienta.",
"Ao criar a sua conta gratuita, junta selos a cada visita. Com 10 selos ganha um serviço grátis. E recebe automaticamente um cupão de 10% de desconto na semana do seu aniversário. 🎂": "Al crear tu cuenta gratuita, juntas sellos en cada visita. Con 10 sellos consigues un servicio gratis. Y recibes automáticamente un cupón de 10% de descuento en la semana de tu cumpleaños. 🎂",
"Sim. Tratamos os seus dados ao abrigo do RGPD e não os vendemos nem cedemos a terceiros. Saiba mais na nossa": "Sí. Tratamos tus datos conforme al RGPD y no los vendemos ni cedemos a terceros. Más información en nuestra",

/* ---------- preçário / nomes de serviços ---------- */
"1ª Aplicação": "1ª Aplicación",
"Abdómen": "Abdomen",
"Afia": "Sacapuntas",
"Alisamento + Threading*": "Alisado + Threading*",
"Alisamento + Tintura*": "Alisado + Tinte*",
"Alisamento de Sobrancelhas*": "Alisado de cejas*",
"Antebraços": "Antebrazos",
"Axilas": "Axilas",
"Axilas + Virilha": "Axilas + Ingles",
"Braços": "Brazos",
"Brow Care": "Brow Care",
"Brow Lamination": "Brow Lamination",
"Brow Lamination + Threading*": "Brow Lamination + Threading*",
"Brow Lamination + Tintura*": "Brow Lamination + Tinte*",
"Brow Lamination*": "Brow Lamination*",
"Brow Vitamin<small>temporariamente indisponível</small>": "Brow Vitamin<small>temporalmente no disponible</small>",
"Buço": "Labio superior",
"Buço + Queixo": "Labio superior + Mentón",
"Caneta de Sobrancelhas": "Rotulador de cejas",
"Consulta de Avaliação (deduz no total)": "Consulta de evaluación (se deduce del total)",
"Consulta de Avaliação<small>deduz no valor total do procedimento</small>": "Consulta de evaluación<small>se deduce del valor total del procedimiento</small>",
"Costas Completas": "Espalda completa",
"Dedos": "Dedos",
"Descoloração de Sobrancelhas (inclui tintura)": "Decoloración de cejas (incluye tinte)",
"Descoloração de Sobrancelhas<small>já inclui a tintura para fechar a cutícula do pelo</small>": "Decoloración de cejas<small>ya incluye el tinte para sellar la cutícula del vello</small>",
"Despigmentação de Sobrancelhas — 1ª Sessão": "Despigmentación de cejas — 1ª Sesión",
"Entre Sobrancelhas": "Entrecejo",
"Escova Spoolie": "Cepillo Spoolie",
"Face<small>inclui maçãs do rosto</small>": "Rostro<small>incluye pómulos</small>",
"Fixante": "Fijador",
"Fortificante de Pestanas": "Fortificante de pestañas",
"Fortificante de Sobrancelhas": "Fortificante de cejas",
"Glúteos": "Glúteos",
"Henna": "Henna",
"Henna + Threading": "Henna + Threading",
"Hidraglos com Cor": "Hidraglos con Color",
"Hidraglos com Cor<small>confirmar valor</small>": "Hidraglos con Color<small>precio a confirmar</small>",
"Hidraglos sem Cor (antigo Lip Vitamin)": "Hidraglos sin Color (antes Lip Vitamin)",
"Hidraglos sem Cor<small>antigo Lip Vitamin</small>": "Hidraglos sin Color<small>antes Lip Vitamin</small>",
"Lash Care": "Lash Care",
"Lifting + Tintura de Pestanas*": "Lifting + Tinte de pestañas*",
"Lifting de Pestanas": "Lifting de pestañas",
"Lifting de Pestanas*": "Lifting de pestañas*",
"Lombar": "Lumbar",
"Lápis Lift & Draw": "Lápiz Lift & Draw",
"Lápis Lift & Draw + Afia": "Lápiz Lift & Draw + Sacapuntas",
"Lápis de Sobrancelhas": "Lápiz de cejas",
"Manutenção até 4 semanas": "Mantenimiento hasta 4 semanas",
"Manutenção até 6 semanas": "Mantenimiento hasta 6 semanas",
"Maçãs do Rosto": "Pómulos",
"Maçãs do Rosto / Contorno da Barba": "Pómulos / Contorno de la barba",
"Meia Perna": "Media pierna",
"Meio das Sobrancelhas": "Entrecejo",
"Micropigmentação de Sobrancelhas": "Micropigmentación de cejas",
"Máscara de Sobrancelhas": "Máscara de cejas",
"Mãos": "Manos",
"Nariz": "Nariz",
"Orelhas": "Orejas",
"Pack 4 sessões Brow Vitamin<small>temporariamente indisponível</small>": "Pack 4 sesiones Brow Vitamin<small>temporalmente no disponible</small>",
"Pack Alisamento + Threading*": "Pack Alisado + Threading*",
"Pack Alisamento + Tintura*": "Pack Alisado + Tinte*",
"Pack Brow Lamination + Threading*": "Pack Brow Lamination + Threading*",
"Pack Brow Lamination + Tintura*": "Pack Brow Lamination + Tinte*",
"Pack Henna + Threading": "Pack Henna + Threading",
"Pack Lifting + Tintura de Pestanas*": "Pack Lifting + Tinte de pestañas*",
"Pack Lifting + Tintura*": "Pack Lifting + Tinte*",
"Pack Permanente + Tintura de Pestanas*": "Pack Permanente + Tinte de pestañas*",
"Pack Tintura + Threading": "Pack Tinte + Threading",
"Patilhas": "Patillas",
"Permanente + Tintura de Pestanas*": "Permanente + Tinte de pestañas*",
"Permanente de Pestanas*": "Permanente de pestañas*",
"Perna Completa": "Pierna completa",
"Pernas + Axilas + Virilha": "Piernas + Axilas + Ingles",
"Pescoço": "Cuello",
"Pestanas Express": "Pestañas Express",
"Pés": "Pies",
"Queixo": "Mentón",
"Remoção (não aplicadas na clínica)": "Retirada (no aplicadas en el estudio)",
"Remoção de Pestanas": "Retirada de pestañas",
"Retoque até 1 ano": "Retoque hasta 1 año",
"Retoque até 60 dias": "Retoque hasta 60 días",
"Rosto Completo": "Rostro completo",
"Rosto Completo<small>inclui sobrancelhas + buço + queixo + face + testa + nariz</small>": "Rostro completo<small>incluye cejas + labio superior + mentón + rostro + frente + nariz</small>",
"Saco Inova Beauty": "Bolsa Inova Beauty",
"Sessão de Manutenção": "Sesión de mantenimiento",
"Sobrancelhas": "Cejas",
"Sobrancelhas + Buço": "Cejas + Labio superior",
"Teen Brows": "Teen Brows",
"Teen Brows + Buço": "Teen Brows + Labio superior",
"Testa": "Frente",
"Threading de Sobrancelhas": "Threading de cejas",
"Tintura": "Tinte",
"Tintura + Threading": "Tinte + Threading",
"Tintura de Pestanas": "Tinte de pestañas",
"Virilha + Perianal": "Ingle + Perianal",
"Virilha Normal": "Ingle normal",

/* ---------- notas <small> das listas ---------- */
"Face": "Rostro",
"Descoloração de Sobrancelhas": "Decoloración de cejas",
"Consulta de Avaliação": "Consulta de evaluación",
"Hidraglos sem Cor": "Hidraglos sin Color",
"Brow Vitamin": "Brow Vitamin",
"Pack 4 sessões Brow Vitamin": "Pack 4 sesiones Brow Vitamin",
"inclui maçãs do rosto": "incluye pómulos",
"inclui sobrancelhas + buço + queixo + face + testa + nariz": "incluye cejas + labio superior + mentón + rostro + frente + nariz",
"já inclui a tintura para fechar a cutícula do pelo": "ya incluye el tinte para sellar la cutícula del vello",
"deduz no valor total do procedimento": "se deduce del valor total del procedimiento",
"confirmar valor": "precio a confirmar",
"antigo Lip Vitamin": "antes Lip Vitamin",
"temporariamente indisponível": "temporalmente no disponible",
"Temporariamente indisponível": "Temporalmente no disponible",

};
